7 neighborhood rating crud
fga-eps-mds/2020.1-stay-safe-user-service pull request #10
Opened 2020-09-18 21:40 UTC by lboaventura25

## Issue 
#7 

## Description
Create the neighborhood rating's CRUD.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-09-18 23:58 UTC, silvasara requested changes

2020-09-18 23:58 UTC, silvasara commented on src/database/models.py
> +
Put the maximum sizes in the Neighborhood model string fields, as described in the issue

2020-09-18 23:58 UTC, silvasara commented on src/utils/validators/rating.py
> +
Adapt update validation in case only one field is being edited

2020-09-18 23:58 UTC, silvasara commented on src/views/rating.py
> +    return decorated_function
Import this decorator from utils/validators/general.py

2020-09-18 23:58 UTC, silvasara commented on src/views/neighborhood.py
> +
Import this decorator from utils/validators/general.py

2020-09-18 23:58 UTC, silvasara commented on src/views/rating.py
> +@rating_blueprint.route('/rating/<int:id_neighborhood>', methods=['POST'])
Protect this endpoint with the decorator validate_token available in utils /validators/general.py and make the necessary changes to the controller functions

2020-09-18 23:58 UTC, silvasara commented on src/views/rating.py
> +    return create_response(response, status)
Separate the get one method and protect the delete and patch methods with the validate_token decorator available at utils/validators/general.py and make the necessary changes to the controller functions

2020-09-19 23:21 UTC, silvasara approved these changes

2020-09-20 00:03 UTC, renan601 approved these changes

2020-09-20 00:03 UTC, merged