Favorite Places Endpoint
fga-eps-mds/2020.1-stay-safe-user-service pull request #42
Opened 2020-10-26 23:13 UTC by herickport

## Issue 
Resolves #39 

## Description

Implemented create, read and delete favorite user locations. 
The endpoints are protected with authentication and it is not possible for a user to change another user's favorite locations.
Updated swagger documentation accordingly.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

## How to validate?

Check in route 'api/places/' if get, post and delete methods are working correctly.
Run the tests.

2020-10-27 13:21 UTC, silvasara requested changes

2020-10-27 13:21 UTC, silvasara commented on src/views/favorite_places.py
> +@validate_header
This decorator is only necessary in POST, PATCH or PUT methods

2020-10-27 13:21 UTC, silvasara commented on src/views/favorite_places.py
> +@validate_header
This decorator is only necessary in POST, PATCH or PUT methods

2020-10-27 13:21 UTC, silvasara commented on src/views/favorite_places.py
> +        request.json, username)
In the function `controller.create_favorire_place`the order of the parameters is defined differently from what is being passed in the function call:
https://github.com/fga-eps-mds/2020.1-stay-safe-user-service/blob/857fbbf086e303de481d55fe2cfd95cc3001307d/src/controllers/favorite_places.py#L16

So when I try to post, I have this error:
![image](https://user-images.githubusercontent.com/30883179/97306468-4b47cb00-183d-11eb-928a-313daa37fb6a.png)

2020-10-27 15:22 UTC, lboaventura25 commented
Thanks, @silvasara. We fix the problems!

2020-10-27 17:44 UTC, silvasara approved these changes

2020-10-31 21:48 UTC, renan601 approved these changes

2020-10-31 21:48 UTC, merged