Increase coverage
fga-eps-mds/2020.1-stay-safe-user-service pull request #48
Opened 2020-10-31 15:40 UTC by lboaventura25

## Issue 
Resolves #46 

## Description
Add more tests and cases of tests.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## How to validate?
Run the tests with
```bash
$ docker-compose run api coverage run -m pytest
```
And check the coverage with command
```bash
$ docker-compose run api coverage report -m
```

2020-10-31 23:53 UTC, silvasara requested changes

2020-10-31 23:53 UTC, silvasara commented on src/controllers/neighborhood.py
> -    return [], 200
it is necessary to return to an empty list with code 200 when there is no record in the bank and when there was no error

2020-10-31 23:53 UTC, silvasara commented on src/controllers/occurrence.py
> -    return [], 200
it is necessary to return to an empty list with code 200 when there is no record in the bank and when there was no error

2020-10-31 23:53 UTC, silvasara commented on src/controllers/user.py
> +
it is necessary to return to an empty list with code 200 when there is no record in the bank and when there was no error

2020-10-31 23:53 UTC, silvasara commented on src/controllers/user.py
> +        return result, code
If we don't have any filter functionality for user, this need not be done. There is no need to test functionality that does not exist

2020-10-31 23:53 UTC, silvasara commented on src/tests/test_config.py
> +        self.assertEqual(config['port'], 8083)
Notes that these settings can be obtained through environment variables, depending on how the deployment is done in the production environment, these variables can change and then these tests will break. I prefer that don't have these tests.

2020-10-31 23:53 UTC, silvasara commented on src/tests/test_user.py
> +    wrong_user_update,
This is not being used

2020-11-01 01:58 UTC, silvasara requested changes

2020-11-01 01:58 UTC, silvasara commented on src/controllers/user.py
> +
this is not necessary as we do not have a user filter.  don't need to test features that we don't have

2020-11-04 01:22 UTC, silvasara approved these changes

2020-11-04 16:50 UTC, renan601 approved these changes

2020-11-04 16:50 UTC, merged